name: C++ Format Checker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      - name: Check C++ formatting
        run: |
          if find . -iname "*.cpp" ! -path "./.git/*" -exec clang-format -style=file -output-replacements-xml {} \; | grep "<replacement " >/dev/null; then exit 1; fi
        shell: bash
      - name: Set up Git user
        run: |
          git config --local user.email "haleyhansen6534@gmail.com"
          git config --local user.name "HHansen6534"
        shell: bash
      - name: Push formatting changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
