name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Show code formatting changes
        run: |
          git diff --name-only HEAD^ HEAD | grep '\.cpp$\|\.h$' | xargs clang-format -style=file --output=diff
          git add .
          git config user.name "HHansen6534"
          git config user.email "haleyhansen6534@gmail.com"
          git commit -m "Format code with ClangFormat"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
          force: true
