name: C++ Format Automater 

on: 
  pull_request:
    branches:
      - main
      - master
  push: 
    branches:
      - main
      - master
      
jobs: 
  format: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      - name: Run clang-format
        run: clang-format -i helloworld.cpp
      - name: Commit formatted code
        run: |
          git config --local user.email "haleyhansen6534@gmail.com"
          git config --local user.name "haley.hansen"
          git commit -a -m "Format C++ code using clang-format"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  

