name: C++ Format Automater 

on: 
  pull_request:
    branches:
      - main
      - master
  push: 
    branches:
      - main
      - master
      
jobs: 
  format: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      - name: Run clang-format
        run: |
          for file in $(find . -name '*.cpp' -o -name '*.h'); do
            clang-format -i $file
            if ! git diff --quiet $file; then
              echo "$file is not formatted correctly."
              exit 1
            fi
          done
      - name: Commit formatted code
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Format C++ code using clang-format"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  

